# Generated by Django 5.0.4 on 2024-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnews',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите автора'),
        ),
        migrations.AlterField(
            model_name='postnews',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Напишите название новости'),
        ),
    ]
