# Generated by Django 5.0.4 on 2024-05-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postnews_author_alter_postnews_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postnews',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'список новостей'},
        ),
    ]
